#!/bin/sh

rm -f *.java *.class

java -jar /usr/local/lib/antlr-4.8-complete.jar -Dlanguage=Java NeobemLexer.g4
java -jar /usr/local/lib/antlr-4.8-complete.jar -Dlanguage=Java NeobemParser.g4
javac *.java
