//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Idfplus.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IIdfplusListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class IdfplusBaseListener : IIdfplusListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_declaration([NotNull] IdfplusParser.Variable_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_declaration([NotNull] IdfplusParser.Variable_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] IdfplusParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] IdfplusParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] IdfplusParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] IdfplusParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.function_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_definition([NotNull] IdfplusParser.Function_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.function_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_definition([NotNull] IdfplusParser.Function_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.import_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_statement([NotNull] IdfplusParser.Import_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.import_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_statement([NotNull] IdfplusParser.Import_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.data_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData_statement([NotNull] IdfplusParser.Data_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.data_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData_statement([NotNull] IdfplusParser.Data_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.idf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdf([NotNull] IdfplusParser.IdfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.idf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdf([NotNull] IdfplusParser.IdfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject([NotNull] IdfplusParser.ObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject([NotNull] IdfplusParser.ObjectContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
