//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Idfplus.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="IdfplusParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IIdfplusListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_declaration([NotNull] IdfplusParser.Variable_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_declaration([NotNull] IdfplusParser.Variable_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] IdfplusParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] IdfplusParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] IdfplusParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] IdfplusParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.template_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplate_statement([NotNull] IdfplusParser.Template_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.template_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplate_statement([NotNull] IdfplusParser.Template_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.map_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMap_statement([NotNull] IdfplusParser.Map_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.map_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMap_statement([NotNull] IdfplusParser.Map_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.import_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_statement([NotNull] IdfplusParser.Import_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.import_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_statement([NotNull] IdfplusParser.Import_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.print_statment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint_statment([NotNull] IdfplusParser.Print_statmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.print_statment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint_statment([NotNull] IdfplusParser.Print_statmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.data_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterData_statement([NotNull] IdfplusParser.Data_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.data_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitData_statement([NotNull] IdfplusParser.Data_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdf([NotNull] IdfplusParser.IdfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdf([NotNull] IdfplusParser.IdfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] IdfplusParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] IdfplusParser.ObjectContext context);
}
