//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Idfplus.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class IdfplusParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, OBJECT=7, MAP_KEYWORD=8, 
		TEMPLATE_KEYWORD=9, FUNCTION_NAME=10, COMMENT=11, OBJECT_TERMINATOR=12, 
		NUMERIC=13, STRING=14, VARIABLE=15, WS=16;
	public const int
		RULE_variable_declaration = 0, RULE_expression = 1, RULE_list = 2, RULE_template_statement = 3, 
		RULE_map_statement = 4, RULE_import_statement = 5, RULE_print_statment = 6, 
		RULE_data_statement = 7, RULE_idf = 8, RULE_object = 9;
	public static readonly string[] ruleNames = {
		"variable_declaration", "expression", "list", "template_statement", "map_statement", 
		"import_statement", "print_statment", "data_statement", "idf", "object"
	};

	private static readonly string[] _LiteralNames = {
		null, "'='", "'['", "']'", "'import'", "'print'", "'data'", null, "'map'", 
		"'template'", null, null, "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, "OBJECT", "MAP_KEYWORD", "TEMPLATE_KEYWORD", 
		"FUNCTION_NAME", "COMMENT", "OBJECT_TERMINATOR", "NUMERIC", "STRING", 
		"VARIABLE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Idfplus.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static IdfplusParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public IdfplusParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public IdfplusParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Variable_declarationContext : ParserRuleContext {
		public ITerminalNode VARIABLE() { return GetToken(IdfplusParser.VARIABLE, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Variable_declarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable_declaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.EnterVariable_declaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.ExitVariable_declaration(this);
		}
	}

	[RuleVersion(0)]
	public Variable_declarationContext variable_declaration() {
		Variable_declarationContext _localctx = new Variable_declarationContext(Context, State);
		EnterRule(_localctx, 0, RULE_variable_declaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 20; Match(VARIABLE);
			State = 21; Match(T__0);
			State = 22; expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(IdfplusParser.STRING, 0); }
		public ITerminalNode NUMERIC() { return GetToken(IdfplusParser.NUMERIC, 0); }
		public ITerminalNode VARIABLE() { return GetToken(IdfplusParser.VARIABLE, 0); }
		public ListContext list() {
			return GetRuleContext<ListContext>(0);
		}
		public Data_statementContext data_statement() {
			return GetRuleContext<Data_statementContext>(0);
		}
		public Map_statementContext map_statement() {
			return GetRuleContext<Map_statementContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 2, RULE_expression);
		try {
			State = 30;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING:
				EnterOuterAlt(_localctx, 1);
				{
				State = 24; Match(STRING);
				}
				break;
			case NUMERIC:
				EnterOuterAlt(_localctx, 2);
				{
				State = 25; Match(NUMERIC);
				}
				break;
			case VARIABLE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 26; Match(VARIABLE);
				}
				break;
			case T__1:
				EnterOuterAlt(_localctx, 4);
				{
				State = 27; list();
				}
				break;
			case T__5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 28; data_statement();
				}
				break;
			case MAP_KEYWORD:
				EnterOuterAlt(_localctx, 6);
				{
				State = 29; map_statement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ListContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_list; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.EnterList(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.ExitList(this);
		}
	}

	[RuleVersion(0)]
	public ListContext list() {
		ListContext _localctx = new ListContext(Context, State);
		EnterRule(_localctx, 4, RULE_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32; Match(T__1);
			State = 36;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__1) | (1L << T__5) | (1L << MAP_KEYWORD) | (1L << NUMERIC) | (1L << STRING) | (1L << VARIABLE))) != 0)) {
				{
				{
				State = 33; expression();
				}
				}
				State = 38;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 39; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Template_statementContext : ParserRuleContext {
		public ITerminalNode TEMPLATE_KEYWORD() { return GetToken(IdfplusParser.TEMPLATE_KEYWORD, 0); }
		public ITerminalNode FUNCTION_NAME() { return GetToken(IdfplusParser.FUNCTION_NAME, 0); }
		public ITerminalNode STRING() { return GetToken(IdfplusParser.STRING, 0); }
		public ITerminalNode[] VARIABLE() { return GetTokens(IdfplusParser.VARIABLE); }
		public ITerminalNode VARIABLE(int i) {
			return GetToken(IdfplusParser.VARIABLE, i);
		}
		public Template_statementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_template_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.EnterTemplate_statement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.ExitTemplate_statement(this);
		}
	}

	[RuleVersion(0)]
	public Template_statementContext template_statement() {
		Template_statementContext _localctx = new Template_statementContext(Context, State);
		EnterRule(_localctx, 6, RULE_template_statement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 41; Match(TEMPLATE_KEYWORD);
			State = 42; Match(FUNCTION_NAME);
			State = 46;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==VARIABLE) {
				{
				{
				State = 43; Match(VARIABLE);
				}
				}
				State = 48;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 49; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Map_statementContext : ParserRuleContext {
		public ITerminalNode MAP_KEYWORD() { return GetToken(IdfplusParser.MAP_KEYWORD, 0); }
		public ITerminalNode FUNCTION_NAME() { return GetToken(IdfplusParser.FUNCTION_NAME, 0); }
		public ListContext list() {
			return GetRuleContext<ListContext>(0);
		}
		public ITerminalNode VARIABLE() { return GetToken(IdfplusParser.VARIABLE, 0); }
		public Map_statementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_map_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.EnterMap_statement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.ExitMap_statement(this);
		}
	}

	[RuleVersion(0)]
	public Map_statementContext map_statement() {
		Map_statementContext _localctx = new Map_statementContext(Context, State);
		EnterRule(_localctx, 8, RULE_map_statement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 51; Match(MAP_KEYWORD);
			State = 52; Match(FUNCTION_NAME);
			State = 55;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__1:
				{
				State = 53; list();
				}
				break;
			case VARIABLE:
				{
				State = 54; Match(VARIABLE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Import_statementContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(IdfplusParser.STRING, 0); }
		public Import_statementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_import_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.EnterImport_statement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.ExitImport_statement(this);
		}
	}

	[RuleVersion(0)]
	public Import_statementContext import_statement() {
		Import_statementContext _localctx = new Import_statementContext(Context, State);
		EnterRule(_localctx, 10, RULE_import_statement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 57; Match(T__3);
			State = 58; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Print_statmentContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Print_statmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_print_statment; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.EnterPrint_statment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.ExitPrint_statment(this);
		}
	}

	[RuleVersion(0)]
	public Print_statmentContext print_statment() {
		Print_statmentContext _localctx = new Print_statmentContext(Context, State);
		EnterRule(_localctx, 12, RULE_print_statment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60; Match(T__4);
			State = 61; expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Data_statementContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(IdfplusParser.STRING, 0); }
		public Data_statementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_data_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.EnterData_statement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.ExitData_statement(this);
		}
	}

	[RuleVersion(0)]
	public Data_statementContext data_statement() {
		Data_statementContext _localctx = new Data_statementContext(Context, State);
		EnterRule(_localctx, 14, RULE_data_statement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 63; Match(T__5);
			State = 64; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdfContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(IdfplusParser.Eof, 0); }
		public ITerminalNode[] COMMENT() { return GetTokens(IdfplusParser.COMMENT); }
		public ITerminalNode COMMENT(int i) {
			return GetToken(IdfplusParser.COMMENT, i);
		}
		public ObjectContext[] @object() {
			return GetRuleContexts<ObjectContext>();
		}
		public ObjectContext @object(int i) {
			return GetRuleContext<ObjectContext>(i);
		}
		public Variable_declarationContext[] variable_declaration() {
			return GetRuleContexts<Variable_declarationContext>();
		}
		public Variable_declarationContext variable_declaration(int i) {
			return GetRuleContext<Variable_declarationContext>(i);
		}
		public Template_statementContext[] template_statement() {
			return GetRuleContexts<Template_statementContext>();
		}
		public Template_statementContext template_statement(int i) {
			return GetRuleContext<Template_statementContext>(i);
		}
		public Import_statementContext[] import_statement() {
			return GetRuleContexts<Import_statementContext>();
		}
		public Import_statementContext import_statement(int i) {
			return GetRuleContext<Import_statementContext>(i);
		}
		public Print_statmentContext[] print_statment() {
			return GetRuleContexts<Print_statmentContext>();
		}
		public Print_statmentContext print_statment(int i) {
			return GetRuleContext<Print_statmentContext>(i);
		}
		public IdfContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_idf; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.EnterIdf(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.ExitIdf(this);
		}
	}

	[RuleVersion(0)]
	public IdfContext idf() {
		IdfContext _localctx = new IdfContext(Context, State);
		EnterRule(_localctx, 16, RULE_idf);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__3) | (1L << T__4) | (1L << OBJECT) | (1L << TEMPLATE_KEYWORD) | (1L << COMMENT) | (1L << VARIABLE))) != 0)) {
				{
				State = 72;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case COMMENT:
					{
					State = 66; Match(COMMENT);
					}
					break;
				case OBJECT:
					{
					State = 67; @object();
					}
					break;
				case VARIABLE:
					{
					State = 68; variable_declaration();
					}
					break;
				case TEMPLATE_KEYWORD:
					{
					State = 69; template_statement();
					}
					break;
				case T__3:
					{
					State = 70; import_statement();
					}
					break;
				case T__4:
					{
					State = 71; print_statment();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 76;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 77; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectContext : ParserRuleContext {
		public ITerminalNode OBJECT() { return GetToken(IdfplusParser.OBJECT, 0); }
		public ObjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_object; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.EnterObject(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIdfplusListener typedListener = listener as IIdfplusListener;
			if (typedListener != null) typedListener.ExitObject(this);
		}
	}

	[RuleVersion(0)]
	public ObjectContext @object() {
		ObjectContext _localctx = new ObjectContext(Context, State);
		EnterRule(_localctx, 18, RULE_object);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 79; Match(OBJECT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x12', 'T', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x5', '\x3', '!', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 
		'%', '\n', '\x4', '\f', '\x4', '\xE', '\x4', '(', '\v', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', 
		'/', '\n', '\x5', '\f', '\x5', '\xE', '\x5', '\x32', '\v', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x5', '\x6', ':', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\a', '\n', 'K', '\n', '\n', '\f', '\n', '\xE', '\n', 
		'N', '\v', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x2', '\x2', '\f', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', 
		'\x10', '\x12', '\x14', '\x2', '\x2', '\x2', 'W', '\x2', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '\x4', ' ', '\x3', '\x2', '\x2', '\x2', '\x6', '\"', 
		'\x3', '\x2', '\x2', '\x2', '\b', '+', '\x3', '\x2', '\x2', '\x2', '\n', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\f', ';', '\x3', '\x2', '\x2', '\x2', 
		'\xE', '>', '\x3', '\x2', '\x2', '\x2', '\x10', '\x41', '\x3', '\x2', 
		'\x2', '\x2', '\x12', 'L', '\x3', '\x2', '\x2', '\x2', '\x14', 'Q', '\x3', 
		'\x2', '\x2', '\x2', '\x16', '\x17', '\a', '\x11', '\x2', '\x2', '\x17', 
		'\x18', '\a', '\x3', '\x2', '\x2', '\x18', '\x19', '\x5', '\x4', '\x3', 
		'\x2', '\x19', '\x3', '\x3', '\x2', '\x2', '\x2', '\x1A', '!', '\a', '\x10', 
		'\x2', '\x2', '\x1B', '!', '\a', '\xF', '\x2', '\x2', '\x1C', '!', '\a', 
		'\x11', '\x2', '\x2', '\x1D', '!', '\x5', '\x6', '\x4', '\x2', '\x1E', 
		'!', '\x5', '\x10', '\t', '\x2', '\x1F', '!', '\x5', '\n', '\x6', '\x2', 
		' ', '\x1A', '\x3', '\x2', '\x2', '\x2', ' ', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', ' ', '\x1C', '\x3', '\x2', '\x2', '\x2', ' ', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', ' ', '\x1E', '\x3', '\x2', '\x2', '\x2', ' ', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '!', '\x5', '\x3', '\x2', '\x2', '\x2', '\"', '&', 
		'\a', '\x4', '\x2', '\x2', '#', '%', '\x5', '\x4', '\x3', '\x2', '$', 
		'#', '\x3', '\x2', '\x2', '\x2', '%', '(', '\x3', '\x2', '\x2', '\x2', 
		'&', '$', '\x3', '\x2', '\x2', '\x2', '&', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\'', ')', '\x3', '\x2', '\x2', '\x2', '(', '&', '\x3', '\x2', 
		'\x2', '\x2', ')', '*', '\a', '\x5', '\x2', '\x2', '*', '\a', '\x3', '\x2', 
		'\x2', '\x2', '+', ',', '\a', '\v', '\x2', '\x2', ',', '\x30', '\a', '\f', 
		'\x2', '\x2', '-', '/', '\a', '\x11', '\x2', '\x2', '.', '-', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x32', '\x3', '\x2', '\x2', '\x2', '\x30', '.', '\x3', 
		'\x2', '\x2', '\x2', '\x30', '\x31', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x32', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\x34', '\a', '\x10', '\x2', '\x2', '\x34', '\t', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\x36', '\a', '\n', '\x2', '\x2', '\x36', 
		'\x39', '\a', '\f', '\x2', '\x2', '\x37', ':', '\x5', '\x6', '\x4', '\x2', 
		'\x38', ':', '\a', '\x11', '\x2', '\x2', '\x39', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\x38', '\x3', '\x2', '\x2', '\x2', ':', '\v', '\x3', 
		'\x2', '\x2', '\x2', ';', '<', '\a', '\x6', '\x2', '\x2', '<', '=', '\a', 
		'\x10', '\x2', '\x2', '=', '\r', '\x3', '\x2', '\x2', '\x2', '>', '?', 
		'\a', '\a', '\x2', '\x2', '?', '@', '\x5', '\x4', '\x3', '\x2', '@', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '\b', '\x2', '\x2', 
		'\x42', '\x43', '\a', '\x10', '\x2', '\x2', '\x43', '\x11', '\x3', '\x2', 
		'\x2', '\x2', '\x44', 'K', '\a', '\r', '\x2', '\x2', '\x45', 'K', '\x5', 
		'\x14', '\v', '\x2', '\x46', 'K', '\x5', '\x2', '\x2', '\x2', 'G', 'K', 
		'\x5', '\b', '\x5', '\x2', 'H', 'K', '\x5', '\f', '\a', '\x2', 'I', 'K', 
		'\x5', '\xE', '\b', '\x2', 'J', '\x44', '\x3', '\x2', '\x2', '\x2', 'J', 
		'\x45', '\x3', '\x2', '\x2', '\x2', 'J', '\x46', '\x3', '\x2', '\x2', 
		'\x2', 'J', 'G', '\x3', '\x2', '\x2', '\x2', 'J', 'H', '\x3', '\x2', '\x2', 
		'\x2', 'J', 'I', '\x3', '\x2', '\x2', '\x2', 'K', 'N', '\x3', '\x2', '\x2', 
		'\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'O', '\x3', '\x2', '\x2', '\x2', 'N', 'L', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'P', '\a', '\x2', '\x2', '\x3', 'P', '\x13', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'R', '\a', '\t', '\x2', '\x2', 'R', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\b', ' ', '&', '\x30', '\x39', 'J', 'L',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
