//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Idfplus.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IIdfplusListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class IdfplusBaseListener : IIdfplusListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_declaration([NotNull] IdfplusParser.Variable_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_declaration([NotNull] IdfplusParser.Variable_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MapExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapExp([NotNull] IdfplusParser.MapExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MapExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapExp([NotNull] IdfplusParser.MapExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParensExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParensExp([NotNull] IdfplusParser.ParensExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParensExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParensExp([NotNull] IdfplusParser.ParensExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VariableExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableExp([NotNull] IdfplusParser.VariableExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VariableExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableExp([NotNull] IdfplusParser.VariableExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StringExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringExp([NotNull] IdfplusParser.StringExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StringExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringExp([NotNull] IdfplusParser.StringExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSub([NotNull] IdfplusParser.AddSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSub([NotNull] IdfplusParser.AddSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NumericExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericExp([NotNull] IdfplusParser.NumericExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NumericExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericExp([NotNull] IdfplusParser.NumericExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Exponientiate</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExponientiate([NotNull] IdfplusParser.ExponientiateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Exponientiate</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExponientiate([NotNull] IdfplusParser.ExponientiateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DataExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataExp([NotNull] IdfplusParser.DataExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DataExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataExp([NotNull] IdfplusParser.DataExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MultDivide</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultDivide([NotNull] IdfplusParser.MultDivideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MultDivide</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultDivide([NotNull] IdfplusParser.MultDivideContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ListExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListExp([NotNull] IdfplusParser.ListExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ListExp</c>
	/// labeled alternative in <see cref="IdfplusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListExp([NotNull] IdfplusParser.ListExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] IdfplusParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] IdfplusParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.template_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplate_statement([NotNull] IdfplusParser.Template_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.template_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplate_statement([NotNull] IdfplusParser.Template_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.map_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMap_statement([NotNull] IdfplusParser.Map_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.map_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMap_statement([NotNull] IdfplusParser.Map_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.import_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_statement([NotNull] IdfplusParser.Import_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.import_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_statement([NotNull] IdfplusParser.Import_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.print_statment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_statment([NotNull] IdfplusParser.Print_statmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.print_statment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_statment([NotNull] IdfplusParser.Print_statmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.data_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData_statement([NotNull] IdfplusParser.Data_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.data_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData_statement([NotNull] IdfplusParser.Data_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.idf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdf([NotNull] IdfplusParser.IdfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.idf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdf([NotNull] IdfplusParser.IdfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfplusParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject([NotNull] IdfplusParser.ObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfplusParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject([NotNull] IdfplusParser.ObjectContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
