//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./ExcelRange.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ExcelRangeParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IExcelRangeListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExcelRangeParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange([NotNull] ExcelRangeParser.RangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExcelRangeParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange([NotNull] ExcelRangeParser.RangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExcelRangeParser.fullrange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFullrange([NotNull] ExcelRangeParser.FullrangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExcelRangeParser.fullrange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFullrange([NotNull] ExcelRangeParser.FullrangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExcelRangeParser.startcell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartcell([NotNull] ExcelRangeParser.StartcellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExcelRangeParser.startcell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartcell([NotNull] ExcelRangeParser.StartcellContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExcelRangeParser.startrowwithcols"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartrowwithcols([NotNull] ExcelRangeParser.StartrowwithcolsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExcelRangeParser.startrowwithcols"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartrowwithcols([NotNull] ExcelRangeParser.StartrowwithcolsContext context);
}
