//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from NeobemParser.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="NeobemParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface INeobemParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declaration([NotNull] NeobemParser.Variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InlineTable</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineTable([NotNull] NeobemParser.InlineTableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionExp([NotNull] NeobemParser.FunctionExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ObjExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjExp([NotNull] NeobemParser.ObjExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParensExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParensExp([NotNull] NeobemParser.ParensExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringExp([NotNull] NeobemParser.StringExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LambdaExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExp([NotNull] NeobemParser.LambdaExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MemberAccessExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberAccessExp([NotNull] NeobemParser.MemberAccessExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSub([NotNull] NeobemParser.AddSubContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NumericExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericExp([NotNull] NeobemParser.NumericExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LetBindingExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetBindingExp([NotNull] NeobemParser.LetBindingExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BooleanLiteralFalseExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanLiteralFalseExp([NotNull] NeobemParser.BooleanLiteralFalseExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RangeExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeExp([NotNull] NeobemParser.RangeExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ListExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListExp([NotNull] NeobemParser.ListExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MapPipeFilterExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapPipeFilterExp([NotNull] NeobemParser.MapPipeFilterExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BooleanLiteralTrueExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanLiteralTrueExp([NotNull] NeobemParser.BooleanLiteralTrueExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VariableExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableExp([NotNull] NeobemParser.VariableExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfExp([NotNull] NeobemParser.IfExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BclExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBclExp([NotNull] NeobemParser.BclExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BooleanExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanExp([NotNull] NeobemParser.BooleanExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Exponientiate</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExponientiate([NotNull] NeobemParser.ExponientiateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicExp</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicExp([NotNull] NeobemParser.LogicExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MultDivide</c>
	/// labeled alternative in <see cref="NeobemParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultDivide([NotNull] NeobemParser.MultDivideContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.functional_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctional_operator([NotNull] NeobemParser.Functional_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.function_application"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_application([NotNull] NeobemParser.Function_applicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.function_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_parameter([NotNull] NeobemParser.Function_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.boolean_exp_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_exp_operator([NotNull] NeobemParser.Boolean_exp_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.if_exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_exp([NotNull] NeobemParser.If_expContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.lambda_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambda_def([NotNull] NeobemParser.Lambda_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] NeobemParser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.idfplus_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdfplus_object([NotNull] NeobemParser.Idfplus_objectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.idfplus_object_property_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdfplus_object_property_def([NotNull] NeobemParser.Idfplus_object_property_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] NeobemParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.import_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_statement([NotNull] NeobemParser.Import_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsOption</c>
	/// labeled alternative in <see cref="NeobemParser.import_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsOption([NotNull] NeobemParser.AsOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OnlyOption</c>
	/// labeled alternative in <see cref="NeobemParser.import_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnlyOption([NotNull] NeobemParser.OnlyOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NotOption</c>
	/// labeled alternative in <see cref="NeobemParser.import_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotOption([NotNull] NeobemParser.NotOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.export_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExport_statement([NotNull] NeobemParser.Export_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.print_statment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint_statment([NotNull] NeobemParser.Print_statmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.log_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLog_statement([NotNull] NeobemParser.Log_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.inline_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInline_table([NotNull] NeobemParser.Inline_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.inline_table_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInline_table_header([NotNull] NeobemParser.Inline_table_headerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.inline_table_header_separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInline_table_header_separator([NotNull] NeobemParser.Inline_table_header_separatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.inline_table_data_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInline_table_data_row([NotNull] NeobemParser.Inline_table_data_rowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionIdfComment</c>
	/// labeled alternative in <see cref="NeobemParser.function_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionIdfComment([NotNull] NeobemParser.FunctionIdfCommentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionObjectDeclaration</c>
	/// labeled alternative in <see cref="NeobemParser.function_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionObjectDeclaration([NotNull] NeobemParser.FunctionObjectDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionDoe2ObjectDeclaration</c>
	/// labeled alternative in <see cref="NeobemParser.function_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDoe2ObjectDeclaration([NotNull] NeobemParser.FunctionDoe2ObjectDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionVariableDeclaration</c>
	/// labeled alternative in <see cref="NeobemParser.function_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionVariableDeclaration([NotNull] NeobemParser.FunctionVariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionPrintStatement</c>
	/// labeled alternative in <see cref="NeobemParser.function_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionPrintStatement([NotNull] NeobemParser.FunctionPrintStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="NeobemParser.function_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] NeobemParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionLogStatement</c>
	/// labeled alternative in <see cref="NeobemParser.function_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionLogStatement([NotNull] NeobemParser.FunctionLogStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IdfComment</c>
	/// labeled alternative in <see cref="NeobemParser.base_idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdfComment([NotNull] NeobemParser.IdfCommentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Doe2Comment</c>
	/// labeled alternative in <see cref="NeobemParser.base_idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoe2Comment([NotNull] NeobemParser.Doe2CommentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ObjectDeclaration</c>
	/// labeled alternative in <see cref="NeobemParser.base_idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectDeclaration([NotNull] NeobemParser.ObjectDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Doe2ObjectDeclaration</c>
	/// labeled alternative in <see cref="NeobemParser.base_idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoe2ObjectDeclaration([NotNull] NeobemParser.Doe2ObjectDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VariableDeclaration</c>
	/// labeled alternative in <see cref="NeobemParser.base_idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] NeobemParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ImportStatement</c>
	/// labeled alternative in <see cref="NeobemParser.base_idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStatement([NotNull] NeobemParser.ImportStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExportStatment</c>
	/// labeled alternative in <see cref="NeobemParser.base_idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExportStatment([NotNull] NeobemParser.ExportStatmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrintStatment</c>
	/// labeled alternative in <see cref="NeobemParser.base_idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStatment([NotNull] NeobemParser.PrintStatmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogStatement</c>
	/// labeled alternative in <see cref="NeobemParser.base_idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogStatement([NotNull] NeobemParser.LogStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.let_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLet_binding([NotNull] NeobemParser.Let_bindingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.let_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLet_expression([NotNull] NeobemParser.Let_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject([NotNull] NeobemParser.ObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.doe2object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoe2object([NotNull] NeobemParser.Doe2objectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.doe2word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoe2word([NotNull] NeobemParser.Doe2wordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.doe2_list_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoe2_list_item([NotNull] NeobemParser.Doe2_list_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.doe2list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoe2list([NotNull] NeobemParser.Doe2listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NeobemParser.idf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdf([NotNull] NeobemParser.IdfContext context);
}
