//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Idf.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="IdfParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IIdfListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfParser.idfFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdfFile([NotNull] IdfParser.IdfFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfParser.idfFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdfFile([NotNull] IdfParser.IdfFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfParser.idfObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdfObject([NotNull] IdfParser.IdfObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfParser.idfObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdfObject([NotNull] IdfParser.IdfObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdfParser.idfHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdfHeader([NotNull] IdfParser.IdfHeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdfParser.idfHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdfHeader([NotNull] IdfParser.IdfHeaderContext context);
}
