name: Build docs

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: mitchpaulus/neobem_doc:0.1.0


    steps:
    - uses: actions/checkout@v4

    - name: Build docs
      run: ./do doc/all
