name: Build docs

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: mitchpaulus/neobem_doc:0.1.0

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Download ANTLR
      run: curl --output antlr-4.13.1-complete.jar https://www.antlr.org/download/antlr-4.13.1-complete.jar
    - name: Compile ANTLR grammars
      run: |
        export ANTLR_JAR="$(pwd)"/antlr-4.13.1-complete.jar
        export CLASSPATH=.:"$(pwd)/antlr-4.13.1-complete.jar"
        cd src/antlr
        ./compile_grammer
        cd excelrange
        ./compile.sh
        cd ..
        cd idf
        ./compile.sh
    - name: Run redo targets
      run: |
        ./do src/Help.cs src/Version.cs test/TestFileDirectory.cs
    - name: Build
      run: |
        dotnet build src
        printf "Searching for nbem executable...\n"
        find . -name nbem -executable
        printf "Adding nbem to PATH...\n"
        realpath "$(dirname "$(find . -name nbem -executable)")" >> $GITHUB_PATH

    - name: Build docs
      run: ./do doc/all

    - name: Store Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: |
          doc/doc.pdf
          doc/doc.html
