name: Build docs

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pandoc texlive-luatex texlive-latex-base

    - name: Build docs
      run: redo doc/all
