name: Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Download ANTLR
      run: curl --output antlr-4.9.3-complete.jar https://www.antlr.org/download/antlr-4.9.3-complete.jar
    - name: Compile ANTLR grammars
      run: |
        java -jar antlr-4.9.3-complete.jar -o src antlr/NeobemLexer.g4
        java -jar antlr-4.9.3-complete.jar -o src -visitor antlr/NeobemParser.g4
        java -jar antlr-4.9.3-complete.jar -o src antlr/excelrange/ExcelRange.g4
        cd antlr/idf/
        java -jar ../../antlr-4.9.3-complete.jar -o ../../src/antlr-idf -Dlanguage=CSharp Idf.g4
    - name: Run redo targets
      run: |
        ./do src/Help.cs src/Version.cs test/TestFileDirectory.cs
    - name: Restore dependencies
      run: |
        dotnet restore src
        dotnet restore test
    - name: Build
      run: |
        dotnet build src --no-restore
        dotnet build test --no-restore
    - name: Test
      run: dotnet test test --no-build --verbosity normal
    - name: Test documentation code samples
      run: |
        PATH=~/work/neobem/neobem/src/bin/Debug/net6.0:"$PATH"
        ./do doc/code_samples/test

